name: Build Flet APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Yeh naya step hai jo server par Flutter install karega
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build APK
        run: echo "y" | flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BhrivimLab-APK
          path: build/apk/
